### ISSUE TITLE
SSA and generics (go1.18)

### ISSUE THREAD

**Issue by ldez** [gostaticanalysis/nilerr#11]
Currently, SSA is not working with generics.

So your linter produces a panic when it is used with generics.

There is an issue open about that in the Go repository: https://github.com/golang/go/issues/48525

Inside golangci-lint, we have disabled your linters: https://github.com/golangci/golangci-lint/issues/2649

You have 2 solutions:
- waiting for a version of SSA that will support generics
- dropping the SSA analyzers and using something else to analyze the code.

Related to https://github.com/golang/go/issues/50558

**Comment by tenntenn** [comment]
https://github.com/golang/go/issues/48525#issuecomment-1128385150

**Comment by ldez** [comment]
SSA has been updated and it seems to work inside golangci-lint.
